import { termsAndConditionsSections } from "./sections"

export const termAndConditions = {
  id: "post_01J81DNNATCFQ5Z8R2ZJAKN7TT",
  type: "page",
  featured_image_id: null,
  title: "Home Page",
  excerpt: null,
  content_mode: "advanced",
  content: null,
  handle: "terms-and-conditions",
  status: "published",
  seo: { image: { alt: { value: "" }, url: "" }, title: "", description: "" },
  product_id: null,
  vendor_id: null,
  archived_at: null,
  published_at: "2024-09-18T01:59:08.891Z",
  last_updated_by_id: "usr_01J81DNN1CZD2HXT09K5YFMCZP",
  root_id: null,
  created_at: "2024-09-18T01:59:08.500Z",
  updated_at: "2024-09-24T22:46:03.391Z",
  authors: [],
  featured_image: null,
  tags: [],
  is_home_page: true,
  last_updated_by: null,
  sections: termsAndConditionsSections,
}
